### ISSUE TITLE
Support subpatchers conversion

### ISSUE THREAD

**Issue by slemouton** [tmhglnd/max-pd-converter#1]
HI ! great project.
Do you plan to deal with subpatchers recursivity ?

**Comment by tmhglnd** [comment]
Sure! That should definitely be part of it, not sure how complicated it will be, we'll see!

**Comment by slemouton** [comment]
I can try to help on that ...

**Comment by tmhglnd** [comment]
Thanks for the help! Seems to work very well! Tested with a few nested subpatchers. Made some small changes in the code so it also works with the `[p]` abbreviation for the `[patcher]`, also cleaned up the code a bit. All is merged in 6282ba4d45e1fa44ff644faf42af97241196c2c8
